package org.example.doaapiproject.models;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Document("campaign")
@Schema(description = "Represents a campaign in the system")
public class Campaign {
    @Id
    @Schema(description = "Represents the automatic id generated by mongo", example = "f51bb4362e")
    private String id;
    @Min(value = 0, message = "the id must be bigger then or equal to zero")
    @Schema(description = "Represents the id of the campaign", example = "0")
    private Integer campaignId;
    @NotNull(message = "the id of the institution cannot be null")
    @Size(message = "the id of the institution must be bigger then or equal to zero")
    @Schema(description = "Represents the id of the institution of the campaign", example = "0")
    private String institutionId;
    @Size(max = 50, message = "the number of characters in the name of the institution must be between 0 and 50")
    @Schema(description = "Represents the name of the institution of the campaign", example = "Institution One")
    private String institutionName;
    @Schema(description = "Represents the photo of the institution of the campaign", example = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACoAAAAoCAYAAACIC2hQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAANXSURBVHgB3ZhNTttAFIDfs5100UqN1CCxdNQQqStgR6FSzQmAEzQ9QdMTQG4AJ2g4AekJSFWglbqArioVkLOslCBl0wXxz+uMcV0nOPZz4oSonxQpst/MfP6beW8QUvKjYOiq2q8pCm4Bge4fbrlEh5Wbs0ZcHAFcENHBbyffXO21epACTBN8XXxZI1B2xd9CZABR23LczbyG20lxrgI7lc7ZBWQtel1c3yXAPUaovFMFTpxlO6svel/bjFhQOEHyMTIlJRxJLy6nqR+YsTxRVbX2YDoYl8VXBieQJ4qwDFOCyN3mxLFExde6AlNCBXjKiWOJ4t0H8qBw7yh7GkmLi/SdE8cUpU8wJTSNmpw4lqhm5/cRoQ0Zg0iN0q8M59GSWO4UoJ0s31Uh2VZUt86NZ4lKSmK5I1LeQgb4kpvcuylhi0rKN5+bgDSR7DiSXjsYg6uF9SoQspe/YLAxJb22MCZpZSeR9NrDBHBlJ5X0+oAJSZLNQlKS6mOKotwRWb34wKKmrqwkvb4gI8xFQ3ft222iuwRGLBAXiv2oUUpZcowiUtQsrOm2Bjqh06t0vg2s8+cFo/BEu60SYS9cIyVxWVwzxAM0xIW007SLFJWZfE6z5PtmBAf9OuhvyXD1bMMUrXT/ZLPcPduBBPx+zaBLcN8vdb/sy/8/F9ZXVBfekYKGd9KllhivPlyiKAOdqdbxgKR3KSgGUc9lh+bimv5P0jtpAAM11x+Ku2tnPtt4oxAeE2LVq1TlT/wX45nDmX8g6pUbAxIDFGSHjpUbTqC59dG9/qSkg9AY1QcCHcnXDO6JImxBQueA7hFkAAIu+5Kx4z1W+0GZEojS+HdnHFhjYegJh+fRFswdFExtgaj4/D/CnBHO/gPR593TfRfhEOYEseFRD69oA0topXNanQdZKbnUPdkLH7u31ktZkWQcwAMRJSmJTErKNyc12QBmzChJycjsyWsww9cgTlISm+aJTdc2zAjNthtx5yfOR2fF/yGqhFaGKGRyDBlRSth5jhcVGXrc7ojYk2JNYzkr34zrR27tQAKxot5WDtJm1CByYfDqJQZ+OVIfIcna2mHVTLIecqx+jRBWUMwEhGpDTCUtSImsWEUpUhVp3mt58a7YJdQ0t8Yp/v4ASgd3Jx9qygkAAAAASUVORK5CYII=")
    private String institutionPhoto;
    @NotNull(message = "description cannot be null")
    @Size(max = 500, message = "the number of characters in the description must be between 0 and 500")
    @Schema(description = "Represents the description of the campaign", example = "This is the campaign")
    private String description;
    @NotNull(message = "images cannot be null")
    @Schema(description = "Represents the images of the campaign", example = "['image1', 'image2']")
    private List<String> images;
    @Pattern(regexp = "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$",
            message = "Invalid date format. The expected format is dd/MM/yyyy")
    @Schema(description = "Represents the date of the end of the campaign", example = "20/07/2007")
    private String endDate;
    @NotNull(message = "local cannot be null")
    @Size(max = 50, message = "the number of characters in the local must be between 0 and 50")
    @Schema(description = "Represents the local of the campaign", example = "São Paulo")
    private String local;

    // construtores
    public Campaign(){}

    public Campaign(String id, Integer campaignId, String institutionId, String institutionName, String institutionPhoto, String description, List<String> images, String endDate, String local) {
        this.id = id;
        this.campaignId = campaignId;
        this.institutionId = institutionId;
        this.institutionName = institutionName;
        this.institutionPhoto = institutionPhoto;
        this.description = description;
        this.images = images;
        this.endDate = endDate;
        this.local = local;
    }

    public Campaign(String institutionId, String description, List<String> images, String endDate, String local) {
        this.institutionId = institutionId;
        this.description = description;
        this.images = images;
        this.endDate = endDate;
        this.local = local;
    }

    // getters e setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    public String getInstitutionName() {
        return institutionName;
    }

    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    public String getInstitutionPhoto() {
        return institutionPhoto;
    }

    public void setInstitutionPhoto(String institutionPhoto) {
        this.institutionPhoto = institutionPhoto;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getLocal() {
        return local;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    public String getInstitutionId() {
        return institutionId;
    }

    public void setInstitutionId(String institutionId) {
        this.institutionId = institutionId;
    }

    // toString
    public String toString() {
        return "Campaign{\n id=" + this.id +
                "\n ,campaignId=" + this.campaignId +
                "\n ,institutionId=" + this.institutionId +
                "\n ,institutionName='" + this.institutionName +
                "'\n ,institutionPhoto='" + this.institutionPhoto +
                "'\n ,description='" + this.description +
                "'\n ,images='" + this.images +
                "'\n ,endDate='" + this.endDate +
                "'\n ,local='" + this.local +
                "'\n}";
    }
}
