package org.example.doaapiproject.models;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document("login")
@Schema(description = "Represents a login in the system")
public class Login {
    @Id
    @Schema(description = "Represents the automatic id generated by mongo", example = "f51bb4362e")
    private String id;

    @Min(value = 0, message = "the id must be bigger then or equal to zero")
    @Schema(description = "Represent the id of the user", example = "0")
    private Integer userId;

    @Email(message = "invalid e-mail")
    @Size(max = 100, message = "the number of characters in the e-mail must be between 0 and 100")
    @Schema(description = "Represents the e-mail of the login", example = "login.24@gmail.com")
    private String email;

    @NotNull(message = "password cannot be null")
    @Pattern(regexp = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
             message = "password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, one number, and one special character")
    @Schema(description = "Represents the password of the login", example = "T3r&vQ6z@")
    private String password;

    // construtores
    public Login(){}

    public Login(String id, String email, String password) {
        this.id = id;
        this.email = email;
        this.password = password;
    }
    public Login(Integer userId, String email, String password) {
        this.userId = userId;
        this.email = email;
        this.password = password;
    }

    // getters e setters


    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // toString
    public String toString() {
        return "Login{\n id=" + this.id +
                "\n ,userId=" + this.userId +
                "\n ,email='" + this.email +
                "\n ,password='" + this.password +
                "'\n}";
    }
}
